name: dart_data_validation
description: A powerful data validation package for Dart that provides a flexible way to validate various data types and structures.
version: 1.0.1
homepage: https://github.com/altaysakarya/dart_data_validation
repository: https://github.com/altaysakarya/dart_data_validation.git
documentation: https://github.com/altaysakarya/dart_data_validation/blob/master/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

license: MIT
